### PR TITLE
Update pypi URL to the new one

### PR DESCRIPTION
**Pull request by stephendonner**
@davehunt r?

Ran tests, got failures at the end I don't understand, but I'm sure you will:

```
Stephens-MacBook-Pro:pytest-fxa stephendonner$ git diff
diff --git a/Pipfile b/Pipfile
index 6b7f776..c4b6446 100644
--- a/Pipfile
+++ b/Pipfile
@@ -1,6 +1,6 @@
 [[source]]
 
-url = "https://pypi.python.org/simple"
+url = "https://pypi.org/simple"
 verify_ssl = true
 name = "pypi"
 
Stephens-MacBook-Pro:pytest-fxa stephendonner$ git add Pipfile 
Stephens-MacBook-Pro:pytest-fxa stephendonner$ git commit -m "Update pypi URL to the new one"
[pypi-url 3e1c481] Update pypi URL to the new one
 1 file changed, 1 insertion(+), 1 deletion(-)
Stephens-MacBook-Pro:pytest-fxa stephendonner$ git push origin pypi-url
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 308 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/stephendonner/pytest-fxa
 * [new branch]      pypi-url -> pypi-url
Stephens-MacBook-Pro:pytest-fxa stephendonner$ tox
GLOB sdist-make: /Users/stephendonner/pytest-fxa/setup.py
py27 create: /Users/stephendonner/pytest-fxa/.tox/py27
py27 installdeps: -rpipenv.txt
py27 inst: /Users/stephendonner/pytest-fxa/.tox/dist/pytest-fxa-1.0.1.dev13+g3e1c481.zip
py27 installed: asn1crypto==0.24.0,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,cryptography==2.2.2,enum34==1.1.6,hawkauthlib==2.0.0,idna==2.6,ipaddress==1.0.22,pathlib2==2.1.0,pipenv==11.10.1,PyBrowserID==0.14.0,pycparser==2.18,PyFxA==0.6.0,pytest-fxa==1.0.1.dev13+g3e1c481,requests==2.18.4,six==1.11.0,urllib3==1.22,virtualenv==16.0.0,virtualenv-clone==0.3.0,WebOb==1.8.1
py27 runtests: PYTHONHASHSEED='3289816'
py27 runtests: commands[0] | pipenv install --dev --skip-lock
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Installing dependencies from Pipfile…
An error occurred while installing flake8-isort==2.5! Will try again.
An error occurred while installing pytest==3.5.1! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:01
Installing initially–failed dependencies…
Success installing flake8-isort==2.5! 0/2 — 00:00:00
Success installing pytest==3.5.1!▉▉▉▉ 1/2 — 00:00:00
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:02
py27 runtests: commands[1] | pipenv run pytest -v -r a
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
======================================= test session starts =======================================
platform darwin -- Python 2.7.13, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /Users/stephendonner/pytest-fxa/.tox/py27/bin/python2.7
cachedir: .pytest_cache
rootdir: /Users/stephendonner/pytest-fxa, inifile:
plugins: fxa-1.0.1.dev13+g3e1c481
collected 6 items                                                                                 

tests/test_plugin.py::test_login PASSED                                                     [ 16%]
tests/test_plugin.py::test_no_digits_in_password PASSED                                     [ 33%]
tests/test_plugin.py::test_destroyed PASSED                                                 [ 50%]
tests/test_plugin.py::test_commandline_email_option PASSED                                  [ 66%]
tests/test_plugin.py::test_fxa_email_env_variable PASSED                                    [ 83%]
tests/test_plugin.py::test_no_email_given PASSED                                            [100%]

==================================== 6 passed in 11.14 seconds ====================================
py36 create: /Users/stephendonner/pytest-fxa/.tox/py36
py36 installdeps: -rpipenv.txt
py36 inst: /Users/stephendonner/pytest-fxa/.tox/dist/pytest-fxa-1.0.1.dev13+g3e1c481.zip
py36 installed: asn1crypto==0.24.0,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,cryptography==2.2.2,hawkauthlib==2.0.0,idna==2.6,pipenv==11.10.1,PyBrowserID==0.14.0,pycparser==2.18,PyFxA==0.6.0,pytest-fxa==1.0.1.dev13+g3e1c481,requests==2.18.4,six==1.11.0,urllib3==1.22,virtualenv==16.0.0,virtualenv-clone==0.3.0,WebOb==1.8.1
py36 runtests: PYTHONHASHSEED='3289816'
py36 runtests: commands[0] | pipenv install --dev --skip-lock
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Installing dependencies from Pipfile…
An error occurred while installing flake8==3.5.0! Will try again.
An error occurred while installing flake8-isort==2.5! Will try again.
An error occurred while installing pytest==3.5.1! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:00
Installing initially–failed dependencies…
Success installing flake8==3.5.0!▉▉▉▉ 0/3 — 00:00:00
Success installing flake8-isort==2.5! 1/3 — 00:00:00
Success installing pytest==3.5.1!▉▉▉▉ 2/3 — 00:00:00
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:02
py36 runtests: commands[1] | pipenv run pytest -v -r a
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
=========================================== test session starts ============================================
platform darwin -- Python 3.6.3, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /Users/stephendonner/pytest-fxa/.tox/py36/bin/python3.6
cachedir: .pytest_cache
rootdir: /Users/stephendonner/pytest-fxa, inifile:
plugins: fxa-1.0.1.dev13+g3e1c481
collected 6 items                                                                                          

tests/test_plugin.py::test_login PASSED                                                              [ 16%]
tests/test_plugin.py::test_no_digits_in_password PASSED                                              [ 33%]
tests/test_plugin.py::test_destroyed PASSED                                                          [ 50%]
tests/test_plugin.py::test_commandline_email_option PASSED                                           [ 66%]
tests/test_plugin.py::test_fxa_email_env_variable PASSED                                             [ 83%]
tests/test_plugin.py::test_no_email_given PASSED                                                     [100%]

======================================== 6 passed in 10.62 seconds =========================================
pypy create: /Users/stephendonner/pytest-fxa/.tox/pypy
ERROR: InterpreterNotFound: pypy
pypy3 create: /Users/stephendonner/pytest-fxa/.tox/pypy3
ERROR: InterpreterNotFound: pypy3
flake8 create: /Users/stephendonner/pytest-fxa/.tox/flake8
flake8 installdeps: -rpipenv.txt
flake8 installed: certifi==2018.4.16,pathlib2==2.1.0,pipenv==11.10.1,six==1.11.0,virtualenv==16.0.0,virtualenv-clone==0.3.0
flake8 runtests: PYTHONHASHSEED='3289816'
flake8 runtests: commands[0] | pipenv install --dev --skip-lock
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:03
flake8 runtests: commands[1] | pipenv run flake8
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
_________________________________________________ summary __________________________________________________
  py27: commands succeeded
  py36: commands succeeded
ERROR:   pypy: InterpreterNotFound: pypy
ERROR:   pypy3: InterpreterNotFound: pypy3
  flake8: commands succeeded
```

### CODE REVIEW

**Review by davehunt — APPROVED** [review]

**Comment by davehunt** [comment]
> Ran tests, got failures at the end I don't understand

It looks like it failed to install a couple of packages but then succeeded on retrying. I see the same on Travis, perhaps PyPI.org is having issues.

**Review by davehunt — APPROVED** [review]

**Comment by stephendonner** [comment]
Thanks, @davehunt - I meant ```ERROR: InterpreterNotFound: pypy``` and ```ERROR: InterpreterNotFound: pypy3``` but I think those are my local issues related to my just-installed xcode 9.4, instead.

**Comment by stephendonner** [comment]
@davehunt mind either granting me write access to this repo, or just merging for me?  Thanks!

**Comment by davehunt** [comment]
> Thanks, @davehunt - I meant ERROR: InterpreterNotFound: pypy and ERROR: InterpreterNotFound: pypy3 but I think those are my local issues related to my just-installed xcode 9.4, instead.

Ah, that just means you don't have pypy or pypy3 installed. I wouldn't worry about those, as Travis CI takes care of them. You can ignore the errors, run tox with `--skip-missing-interpreters`, or install the missing interpreters using pyenv or similar.

**Comment by davehunt** [comment]
> @davehunt mind either granting me write access to this repo, or just merging for me? Thanks!

I don't have admin on this repo. I'll request it, but in the meantime I'll just merge your patch.

**Comment by stephendonner** [comment]
Thanks for both merging and filing the bug!

**Pull request merged**
